FROM node:20

# Create app directory
WORKDIR /app

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install --silent

COPY public /app/public
COPY src /app/src
RUN npm run build

COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider
