FROM node:20

# Create app directory
WORKDIR /app

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
RUN npm install -g serve --silent

COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN serve -s build -l 3000
